### ISSUE TITLE
`applications/delete-application.php` should use `VONAGE_APPLICATION_ID`

### ISSUE THREAD

**Issue by dragonmantank** [Vonage/vonage-php-code-snippets#53]
`applications/delete-application.php` should swap `MESSAGES_APPLICATION_ID` for `VONAGE_APPLICATION_ID`, and the environment file updated.

**Comment by parnus01** [comment]
@dragonmantank  May i do this issue for hacktoberfest ?

**Comment by dragonmantank** [comment]
Yes, feel free! If you see anything else you'd like to work on, don't hesitate to send a pull request.

**Comment by dragonmantank** [comment]
I saw that you opened #54 as part of this, then closed it. Feel free to re-open that PR if you want. I did also notice that it looks like `applications/get-application.php` and `applications/update-application.php` also use that constant, so we should update those files at the same time. 

Thanks for the help and willingness to work on this!

**Comment by parnus01** [comment]
Sure i will re-open PR after 1 Oct.

**Comment by dragonmantank** [comment]
Handled in #57
