### ISSUE TITLE
How can i get all OwnedNumbers, not only ten?

### ISSUE THREAD

**Issue by erimeilis** [Vonage/vonage-php-code-snippets#69]
Need do get the full list of owned numbers, pages. So is there any option of offset/size for ->numbers()->searchOwned()?

**Comment by SecondeJK** [comment]
Hi @erimeilis,
This is done by passing in a filter. For example:

```
$ownedNumberFilter = new \Vonage\Numbers\Filter\OwnedNumbers();
$ownedNumberFilter->setPageSize(50);
$client->numbers->searchOwned($ownedNumberFilter());
```
