### ISSUE TITLE
Vonage instead of Nexmo should be used

### ISSUE THREAD

**Issue by ahmad-511** [Vonage/vonage-php-code-snippets#71]
In Vonage / vonage-php-code-snippets, Nexmo is used to instantiate a signature

https://github.com/Vonage/vonage-php-code-snippets/blob/f577cb31b41ba4128cef153b315132febfd3125d/sms/verify-signed-sms.php#L9

`$signature = new Nexmo\Client\Signature`
should be 
`$signature = new Vonage\Client\Signature`

**Comment by SecondeJK** [comment]
Oof, good catch. I'll get this into the PR I'm about to put out.
